// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package classicmodels

import (
	"context"
)

const getCustomer = `-- name: GetCustomer :one
SELECT customernumber, customername, contactlastname, contactfirstname, phone, addressline1, addressline2, city, state, postalcode, country, salesrepemployeenumber, creditlimit FROM customers LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer)
	var i Customer
	err := row.Scan(
		&i.Customernumber,
		&i.Customername,
		&i.Contactlastname,
		&i.Contactfirstname,
		&i.Phone,
		&i.Addressline1,
		&i.Addressline2,
		&i.City,
		&i.State,
		&i.Postalcode,
		&i.Country,
		&i.Salesrepemployeenumber,
		&i.Creditlimit,
	)
	return i, err
}
